### ISSUE TITLE
"Feature" request - sort alphabetically

### ISSUE THREAD

**Issue by talonx** [kaypee90/awesome-open-standards#2]
It would be great if the list were sorted alphabetically - makes it easier to find a standard.

**Comment by Lewiscowles1986** [comment]
Do you think that a filter text input box might be easier to use, and would be a vector for future search / filtering efforts?

**Comment by kaypee90** [comment]
> Do you think that a filter text input box might be easier to use, and would be a vector for future search / filterin

I will create this as an issue for improvements. To make discoverability easier.
